# fly.toml app configuration file generated for r-chapy-server on 2023-08-03T22:59:57+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "r-chapy-server"
primary_region = "arn"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
