# fly.toml app configuration file generated for chapy-server-beta on 2023-10-07T19:02:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chapy-server"
primary_region = "arn"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
